package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Consultas generated by hbm2java
 */

//@Entity
@Embeddable
@Table(name = "CONSULTAS")
public class Consulta  implements java.io.Serializable {
   
@Id @GeneratedValue
@Column(name = "idCONSULTAS")
    private Integer idConsultas;  

@Column(name = "fecha_y_hora")
@Temporal(javax.persistence.TemporalType.DATE)
     private Date fechaYHora;

@Column(name = "resumen")
     private String resumen;

@EmbeddedId
@OneToMany 
@Column(name = "PACIENTES_id")
     private Integer pacienteId;

@EmbeddedId
@OneToMany 
@Column(name = "PACIENTES_tipo_id")
     private String pacienteTipoId;

    public Consulta() {
    }

    public Consulta(Date fechaYHora, String resumen, Integer pacienteId, String pacienteTipoId) {       
       this.fechaYHora = fechaYHora;
       this.resumen = resumen;
       this.pacienteId = pacienteId;
       this.pacienteTipoId = pacienteTipoId;
    }
    
    public Integer getIdConsultas() {
        return this.idConsultas;
    }
    
    public void setIdConsultas(Integer idConsultas) {
        this.idConsultas = idConsultas;
    }

    public Date getFechaYHora() {
        return this.fechaYHora;
    }
    
    public void setFechaYHora(Date fechaYHora) {
        this.fechaYHora = fechaYHora;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    public Integer getPacienteId() {
        return pacienteId;
    }

    public void setPacienteId(Integer pacienteId) {
        this.pacienteId = pacienteId;
    }

    public String getPacienteTipoId() {
        return pacienteTipoId;
    }

    public void setPacienteTipoId(String pacienteTipoId) {
        this.pacienteTipoId = pacienteTipoId;
    }
}