package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name="CURSOS")
public class Curso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String nemonico;
     private Set<Estudiante> estudiantes = new HashSet<>(0);

    public Curso() {
    }

	
    public Curso(int id, String nombre, String nemonico) {
        this.id = id;
        this.nombre = nombre;
        this.nemonico = nemonico;
    }
    
    public Curso(int id, String nombre, String nemonico, Set<Estudiante> estudianteses) {
       this.id = id;
       this.nombre = nombre;
       this.nemonico = nemonico;
       this.estudiantes = estudianteses;
    }
   
    @Id
    @Column(name="id")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="nemonico")
    public String getNemonico() {
        return this.nemonico;
    }
    
    public void setNemonico(String nemonico) {
        this.nemonico = nemonico;
    }
    
    @ManyToMany(cascade = CascadeType.ALL)
    @JoinTable(name="ESTUDIANTES_CURSOS",joinColumns={@JoinColumn(name="CURSOS_id", referencedColumnName="id", nullable = false)},
               inverseJoinColumns= {@JoinColumn(name="ESTUDIANTES_codigo", referencedColumnName="codigo", nullable = false)}
              )    
    public Set<Estudiante> getEstudianteses() {
        return this.estudiantes;
    }
    
    public void setEstudianteses(Set<Estudiante> estudianteses) {
        this.estudiantes = estudianteses;
    }




}


